---
version: '2.1'

services:
  radiusd:
    image: karbon15/freeradius3
    command: -f -l stdout -d /etc/raddb
    ports:
      - "1812:1812/udp"
      - "1812:1812"
    expose:
     - "1812"
    tty: true
    read_only: true
    cap_drop:
      - all
    pids_limit: 10
    cpu_shares: 512
    mem_limit: 100M
    shm_size: 16M
    expose:
     - "1812"
    volumes:
     - /opt/containers/radiusd/volumes/freeradius:/etc/raddb
